### ISSUE TITLE
Multiplayer framework

### ISSUE THREAD

**Issue by dhuan008** [Andymendez100/YDEKM#14]
Build the multiplayer framework.
-Currently only need functionally for 2 players. Please structure for expansion if possible.

**Comment by dhuan008** [comment]
Feel free to add yourself or take over this issue if you wish.

**Comment by dhuan008** [comment]
Why is this low priority? This is required for two players to connect to each other. Also required for video between 2 different computers.

**Comment by Andymendez100** [comment]
I thought this was for the more than 2 couples? Thought you guys got the video working on thursday?
