### ISSUE TITLE
Create Account: page layout and functionality 

### ISSUE THREAD

**Issue by dhuan008** [Andymendez100/YDEKM#15]
Should be a option in the hamburger menu.
-Design is open. 
-Form should contain a submit button with relevant input fields.
-On submit, user info should be saved to database.

Related to Issue #2 Database Schema

**Comment by saynegrojas** [comment]
These need to be on the same page. Check google docs for example.

Sign up +1 Login:
email: username:
username: password"
password:
confirm password:
